// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using computerseekho.Repositories;

#nullable disable

namespace computerseekho.Migrations
{
    [DbContext(typeof(ComputerSeekhoDbContext))]
    partial class ComputerSeekhoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("computerseekho.Models.AdminEnquiry", b =>
                {
                    b.Property<int>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AlternateMobile")
                        .HasColumnType("bigint");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnquirerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnquirerQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnquiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IsActive")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long?>("Mobile")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnquiryId");

                    b.ToTable("adminEnquiry");
                });

            modelBuilder.Entity("computerseekho.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<DateTime>("AnnouncementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnnouncementText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isValid")
                        .HasColumnType("bit");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("computerseekho.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int");

                    b.Property<decimal>("CourseIsActive")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseSyllabus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("computerseekho.Models.StaffMaster", b =>
                {
                    b.Property<int>("Staffid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staffid"));

                    b.Property<string>("Staffemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Staffmobile")
                        .HasColumnType("bigint");

                    b.Property<string>("Staffname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staffrole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Staffid");

                    b.ToTable("staffmasters");
                });
#pragma warning restore 612, 618
        }
    }
}
