// <auto-generated />
using AuthApp.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthApp.Models.AdminLogin", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("AdminLogins");
                });

            modelBuilder.Entity("AuthApp.Models.StaffMaster", b =>
                {
                    b.Property<int>("Staffid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staffid"));

                    b.Property<string>("Staffemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Staffmobile")
                        .HasColumnType("bigint");

                    b.Property<string>("Staffname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staffrole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Staffid");

                    b.ToTable("StaffMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
